server {
    listen 80 default_server;
    server_name webapp.lab2.local 10.20.2.10;

    root /srv/data/apps/webapp;
    index index.php index.html;

    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options DENY;

    access_log /var/log/nginx/webapp_access.log;
    error_log  /var/log/nginx/webapp_error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php-fpm.sock;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }
}
