authoritative;
default-lease-time 600;
max-lease-time 7200;

subnet 10.20.2.0 netmask 255.255.255.0 {
    range 10.20.2.50 10.20.2.100;
    option routers 10.20.2.1;
    option domain-name "lab2.local";
    option domain-name-servers 10.20.2.1;
}

# Reservation: cli01 selalu dapat IP tetap
host cli01 {
    hardware ethernet 08:00:27:65:ff:50;
    fixed-address 10.20.2.10;
}
